### ISSUE TITLE
Question? About _n:1,2,4d

### ISSUE THREAD

**Issue by fxbenard** [stephenharris/grunt-checktextdomain#5]
Hey, more a question than an issue but maybe not
why are you using
_n:1,2,4d

should'nt it be

_n:1,2,3d

Thanks

**Comment by stephenharris** [comment]
Hi @fxbenard. The first two arguments of `_n` are the translatable strings (singular & plural). The third is the number of 'items' to determine which translated string to use. The fourth is the text domain, which is why this has the `4d` specifier. (See [codex](https://codex.wordpress.org/Function_Reference/_n))

**Comment by fxbenard** [comment]
Lovely, thanks to you and to the codex for this explanation
